/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.JOptionPane;
import project.ConnectionProvider;
import javax.swing.table.DefaultTableModel;

/**
 *
 * /**
 *
 * @author hp
 */
public class Billing_Point extends javax.swing.JFrame {

    public int finalTotal = 0;

    /**
     * Creates new form CreateBill
     */
    public Billing_Point() {
        initComponents();
        SimpleDateFormat dFormate = new SimpleDateFormat("dd-MM-YYYY");
        java.util.Date date = new java.util.Date();
        jTextField9.setText(dFormate.format(date));

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        jTextField8.setText(dtf.format(now));

        int min = 1000;
        int max = 5000;

        Random random = new Random();

        int value = random.nextInt(max - min + 1) + min;

        bill_no.setText(String.valueOf(value));
    }

    private void savebill() {

        Connection con = ConnectionProvider.getCon();

        Date date = new Date(new java.util.Date().getTime());

        try {

//        String name = jTextField1.getText();
            for (int i = 0; i < jTable2.getRowCount(); i++) {

                String n = jTable2.getValueAt(i, 0).toString();
                String c = jTable2.getValueAt(i, 1).toString();
                String p = jTable2.getValueAt(i, 2).toString();
                String q = jTable2.getValueAt(i, 3).toString();
                String s = jTable2.getValueAt(i, 4).toString();
                String billno = bill_no.getText();
                String cus_name = this.cus_name.getText();
                int pi = Integer.parseInt(jTable2.getValueAt(i, 5).toString());

                String sql = "Insert into billing(name,billId,category,price,quantity,total,create_date,proId,customer_name) values (?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, n);
                ps.setString(2, billno);
                ps.setString(3, c);
                ps.setString(4, p);
                ps.setString(5, q);
                ps.setString(6, s);
                ps.setDate(7, date);
                ps.setInt(8, pi);
                ps.setString(9, cus_name);

                int updatedRowCount = ps.executeUpdate();

            }

        } catch (HeadlessException | SQLException e) {
            e.getMessage();

        }
    }

    public void UpdateProductCount() {
        String proid = productIdTextField.getText();
        String qty = quantityTextField.getText();
        try (Connection con = ConnectionProvider.getCon();
                PreparedStatement ps = con.prepareStatement("UPDATE product_tbl SET proQty = proQty - ? WHERE proId = ?")) {

            // Assuming qty is an integer, you may need to parse it based on your requirements
            ps.setInt(1, Integer.parseInt(qty));
            ps.setString(2, proid);

            int rowCount = ps.executeUpdate();

            if (rowCount > 0) {
                JOptionPane.showMessageDialog(this, "Product Count Updated!");
            } else {
                JOptionPane.showMessageDialog(this, "Cannot Update Product Count. Product ID not found or count is already 0.");
            }

        } catch (SQLException | NumberFormatException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        proid = new javax.swing.JLabel();
        bill_no = new javax.swing.JTextField();
        billNo = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        proQty = new javax.swing.JLabel();
        productIdTextField = new javax.swing.JTextField();
        proName = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        category = new javax.swing.JLabel();
        categoryCombo = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        tme = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        dt = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField7 = new javax.swing.JTextField();
        contact = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        prodetail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        price = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        caldetail = new javax.swing.JLabel();
        Paid = new javax.swing.JLabel();
        Return = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        proid.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        proid.setForeground(new java.awt.Color(255, 102, 0));
        proid.setText(" Product Id");

        bill_no.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        billNo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        billNo.setForeground(new java.awt.Color(255, 102, 0));
        billNo.setText("Bill No.");

        cus_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cus_name.setForeground(new java.awt.Color(255, 102, 0));
        cus_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_nameActionPerformed(evt);
            }
        });

        proQty.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        proQty.setForeground(new java.awt.Color(255, 102, 0));
        proQty.setText("Quantity");

        productIdTextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        productIdTextField.setForeground(new java.awt.Color(255, 102, 0));
        productIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdTextFieldActionPerformed(evt);
            }
        });

        proName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        proName.setForeground(new java.awt.Color(255, 102, 0));
        proName.setText("Product Name");

        quantityTextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        quantityTextField.setForeground(new java.awt.Color(255, 102, 0));

        category.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        category.setForeground(new java.awt.Color(255, 102, 0));
        category.setText("Category");

        categoryCombo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        categoryCombo.setForeground(new java.awt.Color(255, 102, 0));
        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grocery", "Beverage", "Cosmetic", "Electronics", "Utensils", "Decorations", "Clothing", "Baby point", "Accessories" }));

        save.setBackground(new java.awt.Color(255, 102, 0));
        save.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.setBorder(null);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("BILLING POINT");

        delete.setBackground(new java.awt.Color(255, 102, 0));
        delete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("delete");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 102, 0));
        clear.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.setBorder(null);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(255, 102, 0));
        add.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.setBorder(null);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tme.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tme.setForeground(new java.awt.Color(255, 102, 0));
        tme.setText("Time");

        name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 102, 0));
        name.setText("Name");

        productNameTextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        productNameTextField.setForeground(new java.awt.Color(255, 102, 0));

        total.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 102, 0));
        total.setText("Total");

        jTextField6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 102, 0));

        dt.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        dt.setForeground(new java.awt.Color(255, 102, 0));
        dt.setText("Date");

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 102, 0));
        jTextField7.setText("Buyer Details");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        contact.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 102, 0));
        contact.setText("Contact No.");

        jTextField10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 102, 0));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 102, 0));
        email.setText("Email");

        address.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 102, 0));
        address.setText("Address");

        jTextField11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 102, 0));

        jTextField12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 102, 0));

        prodetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prodetail.setForeground(new java.awt.Color(255, 102, 0));
        prodetail.setText("Product Detail");
        prodetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodetailActionPerformed(evt);
            }
        });

        price.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        price.setForeground(new java.awt.Color(255, 102, 0));
        price.setText("Price");

        priceTextField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        priceTextField.setForeground(new java.awt.Color(255, 102, 0));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Price", "Quantity", "Total", "proId"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        caldetail.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        caldetail.setForeground(new java.awt.Color(255, 102, 0));
        caldetail.setText("Calculation Detail");

        Paid.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Paid.setForeground(new java.awt.Color(255, 102, 0));
        Paid.setText("Paid Amt");

        Return.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Return.setForeground(new java.awt.Color(255, 102, 0));
        Return.setText("Return Amt");

        jTextField14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 102, 0));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jTextField15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(name)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(contact)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(email)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(address)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(proid)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(proName)
                                    .addGap(10, 10, 10)
                                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(category)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(price)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(proQty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prodetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(361, 361, 361)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tme, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(billNo))
                                .addGap(80, 80, 80)))
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(180, 180, 180))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bill_no, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(caldetail)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Paid)
                                        .addGap(55, 55, 55)
                                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Return)
                                        .addGap(38, 38, 38)
                                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(dt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tme))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bill_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billNo))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email)
                    .addComponent(address)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(prodetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proid)
                    .addComponent(productIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proName)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proQty)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(category)
                    .addComponent(categoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(caldetail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(total))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Paid)
                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Return)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\Supermarket\\image\\cancel_190406.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Billing_Point().setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        UpdateProductCount();
        String name = cus_name.getText();
        String contactNo = jTextField10.getText();
        String email = jTextField12.getText();
        String address = jTextField11.getText();
        String billId = bill_no.getText();
        String path = "D:\\SuperMarketBillPDF";
        Document doc = new Document();
        try {

            PdfWriter.getInstance(doc, new FileOutputStream(new File(path + File.separator + Math.random() + jTextField9.getText() + ".pdf")));
            doc.open();
            Paragraph paragraph1 = new Paragraph("                       Family Point(Supermarket Management System)\n                          Contact Number:(+977)9864906246\n\n");
            doc.add(paragraph1);
            Paragraph paragraph2 = new Paragraph("Date & Time:" + jTextField9.getText() + "     " + jTextField8.getText() + "Bill id:"+bill_no.getText()+"\nBuyer Details:\nName:" + name + "\nContact No" + contactNo + "\nEmail:" + email + "\nAddress" + address +  "\n\n");
            doc.add(paragraph2);
            PdfPTable tbl = new PdfPTable(6);
            tbl.addCell("Name");
            tbl.addCell("Category");
            tbl.addCell("Price");
            tbl.addCell("Quantity");
            tbl.addCell("Sub Total");
            for (int i = 0; i < jTable2.getRowCount(); i++) {
                String n = jTable2.getValueAt(i, 0).toString();
                String c = jTable2.getValueAt(i, 1).toString();
                String p = jTable2.getValueAt(i, 2).toString();
                String q = jTable2.getValueAt(i, 3).toString();
                String s = jTable2.getValueAt(i, 4).toString();
                tbl.addCell(n);
                tbl.addCell(c);
                tbl.addCell(p);
                tbl.addCell(q);
                tbl.addCell(s);

            }
            doc.add(tbl);
            Paragraph paragraph3 = new Paragraph("\nTotal" + jTextField6.getText() + "\nPaid Amount" + jTextField14.getText() + "\nReturn Amount" + jTextField15.getText() + "\n\nThank You For Shopping With US !Please Do Visit Us Again.\nFamily Point");
            doc.add(paragraph3);
            doc.close();

            JOptionPane.showMessageDialog(null, "Bill Generated");
            setVisible(true);
            new Billing_Point().setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String name = productNameTextField.getText();
        int price = Integer.parseInt(priceTextField.getText());
        int quantity = Integer.parseInt(quantityTextField.getText());
        int total = price * quantity;
        int proId = Integer.parseInt(productIdTextField.getText());

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{name, categoryCombo.getSelectedItem(), price, quantity, total, proId});
        finalTotal = finalTotal + total;
        String finalTotal1 = String.valueOf(finalTotal);
        jTextField6.setText(finalTotal1);

        savebill();

    }//GEN-LAST:event_addActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void prodetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodetailActionPerformed

    private void cus_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_nameActionPerformed
        // TODO add your handling code here:
        String name = cus_name.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from new_buyer where name like '" + name + "%'");
            if (rs.next()) {
                cus_name.setText(rs.getString(1));
                jTextField10.setText(rs.getString(2));
                jTextField12.setText(rs.getString(3));
                jTextField11.setText(rs.getString(4));
            } else {
                jTextField10.setText("");
                jTextField12.setText("");
                jTextField11.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cus_nameActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
        String contactNo = jTextField10.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from new_buyer where contactNo like '" + contactNo + "%'");
            if (rs.next()) {
                cus_name.setText(rs.getString(1));
                jTextField10.setText(rs.getString(2));
                jTextField12.setText(rs.getString(3));
                jTextField11.setText(rs.getString(4));
            } else {
                cus_name.setText("");
                jTextField12.setText("");
                jTextField11.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jTextField10ActionPerformed

    private void productIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdTextFieldActionPerformed
        // TODO add your handling code here:
        String proid = productIdTextField.getText();
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from product_tbl where proId='" + proid + "'");
            if (rs.next()) {
                productIdTextField.setText(rs.getString(1));
                productNameTextField.setText(rs.getString(2));
                categoryCombo.setSelectedItem(rs.getString(3));
                quantityTextField.setText("1");
                priceTextField.setText(rs.getString(4));
            } else {
                productNameTextField.setText("");
                categoryCombo.setSelectedItem("");
                quantityTextField.setText("");
                priceTextField.setText("");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_productIdTextFieldActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
        String paidAmount = jTextField14.getText();
        int z = Integer.parseInt(paidAmount);
        finalTotal = z - finalTotal;
        String finalTotal1 = String.valueOf(finalTotal);
        jTextField15.setText(finalTotal1);
        jTextField15.setEditable(false);
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jPanel2 = new javax.swing.JPanel();
//        proId = new javax.swing.JLabel();
//        jTextField1 = new javax.swing.JTextField();
//        billNo = new javax.swing.JLabel();
//        jTextField2 = new javax.swing.JTextField();
//        proQty = new javax.swing.JLabel();
//        jTextField3 = new javax.swing.JTextField();
//        proName = new javax.swing.JLabel();
//        jTextField4 = new javax.swing.JTextField();
//        category = new javax.swing.JLabel();
//        proCat = new javax.swing.JComboBox<>();
//        print = new javax.swing.JButton();
//        jLabel9 = new javax.swing.JLabel();
//        delete1 = new javax.swing.JButton();
//        delete2 = new javax.swing.JButton();
//        delete3 = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jTable1 = new javax.swing.JTable();
//        jTextField8 = new javax.swing.JTextField();
//        time = new javax.swing.JLabel();
//        name = new javax.swing.JLabel();
//        jTextField5 = new javax.swing.JTextField();
//        total = new javax.swing.JLabel();
//        jTextField6 = new javax.swing.JTextField();
//        date = new javax.swing.JLabel();
//        jTextField9 = new javax.swing.JTextField();
//        jSeparator1 = new javax.swing.JSeparator();
//        jTextField7 = new javax.swing.JTextField();
//        contact = new javax.swing.JLabel();
//        jTextField10 = new javax.swing.JTextField();
//        email = new javax.swing.JLabel();
//        address = new javax.swing.JLabel();
//        jTextField11 = new javax.swing.JTextField();
//        jTextField12 = new javax.swing.JTextField();
//        prodetail = new javax.swing.JTextField();
//        jSeparator2 = new javax.swing.JSeparator();
//        price = new javax.swing.JLabel();
//        jTextField13 = new javax.swing.JTextField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
//
//        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
//
//        proId.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        proId.setForeground(new java.awt.Color(255, 102, 0));
//        proId.setText(" Product Id");
//
//        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField1.setForeground(new java.awt.Color(255, 102, 0));
//
//        billNo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        billNo.setForeground(new java.awt.Color(255, 102, 0));
//        billNo.setText("Bill No.");
//
//        jTextField2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField2.setForeground(new java.awt.Color(255, 102, 0));
//
//        proQty.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        proQty.setForeground(new java.awt.Color(255, 102, 0));
//        proQty.setText("Quantity");
//
//        jTextField3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField3.setForeground(new java.awt.Color(255, 102, 0));
//
//        proName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        proName.setForeground(new java.awt.Color(255, 102, 0));
//        proName.setText("Product Name");
//
//        jTextField4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField4.setForeground(new java.awt.Color(255, 102, 0));
//
//        category.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        category.setForeground(new java.awt.Color(255, 102, 0));
//        category.setText("Category");
//
//        proCat.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        proCat.setForeground(new java.awt.Color(255, 102, 0));
//        proCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grocery", "Beverage", "Cosmetic", "Electronics", "Utensils", "Decorations", "Clothing", "Baby point", "Accessories" }));
//
//        print.setBackground(new java.awt.Color(255, 102, 0));
//        print.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        print.setForeground(new java.awt.Color(255, 255, 255));
//        print.setText("Print");
//        print.setBorder(null);
//        print.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                printActionPerformed(evt);
//            }
//        });
//
//        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
//        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
//        jLabel9.setText("BILLING POINT");
//
//        delete1.setBackground(new java.awt.Color(255, 102, 0));
//        delete1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        delete1.setForeground(new java.awt.Color(255, 255, 255));
//        delete1.setText("Edit");
//        delete1.setBorder(null);
//        delete1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                delete1ActionPerformed(evt);
//            }
//        });
//
//        delete2.setBackground(new java.awt.Color(255, 102, 0));
//        delete2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        delete2.setForeground(new java.awt.Color(255, 255, 255));
//        delete2.setText("Clear");
//        delete2.setBorder(null);
//        delete2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                delete2ActionPerformed(evt);
//            }
//        });
//
//        delete3.setBackground(new java.awt.Color(255, 102, 0));
//        delete3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        delete3.setForeground(new java.awt.Color(255, 255, 255));
//        delete3.setText("Add");
//        delete3.setBorder(null);
//        delete3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                delete3ActionPerformed(evt);
//            }
//        });
//
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//
//            },
//            new String [] {
//                "Quantity", "Name", "Price", "Total Price"
//            }
//        ));
//        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jTable1MouseClicked(evt);
//            }
//        });
//        jScrollPane1.setViewportView(jTable1);
//
//        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//
//        time.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        time.setForeground(new java.awt.Color(255, 102, 0));
//        time.setText("Time");
//
//        name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        name.setForeground(new java.awt.Color(255, 102, 0));
//        name.setText("Name");
//
//        jTextField5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField5.setForeground(new java.awt.Color(255, 102, 0));
//
//        total.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        total.setForeground(new java.awt.Color(255, 102, 0));
//        total.setText("Total");
//
//        jTextField6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField6.setForeground(new java.awt.Color(255, 102, 0));
//
//        date.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        date.setForeground(new java.awt.Color(255, 102, 0));
//        date.setText("Date");
//
//        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
//        jTextField9.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField9ActionPerformed(evt);
//            }
//        });
//
//        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//        jTextField7.setForeground(new java.awt.Color(255, 102, 0));
//        jTextField7.setText("Buyer Details");
//        jTextField7.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField7ActionPerformed(evt);
//            }
//        });
//
//        contact.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        contact.setForeground(new java.awt.Color(255, 102, 0));
//        contact.setText("Contact No.");
//
//        jTextField10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField10.setForeground(new java.awt.Color(255, 102, 0));
//
//        email.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        email.setForeground(new java.awt.Color(255, 102, 0));
//        email.setText("Email");
//
//        address.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        address.setForeground(new java.awt.Color(255, 102, 0));
//        address.setText("Address");
//
//        jTextField11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField11.setForeground(new java.awt.Color(255, 102, 0));
//
//        jTextField12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField12.setForeground(new java.awt.Color(255, 102, 0));
//
//        prodetail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//        prodetail.setForeground(new java.awt.Color(255, 102, 0));
//        prodetail.setText("Product Detail");
//        prodetail.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                prodetailActionPerformed(evt);
//            }
//        });
//
//        price.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
//        price.setForeground(new java.awt.Color(255, 102, 0));
//        price.setText("Price");
//
//        jTextField13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
//        jTextField13.setForeground(new java.awt.Color(255, 102, 0));
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
//            .addComponent(jSeparator2)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGap(361, 361, 361)
//                        .addComponent(jLabel9))
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(prodetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGap(169, 169, 169)
//                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addGap(0, 0, Short.MAX_VALUE))
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addGap(31, 31, 31)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                        .addGap(0, 0, Short.MAX_VALUE)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addComponent(total)
//                                .addGap(28, 28, 28)
//                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                    .addComponent(billNo)
//                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(32, 32, 32)
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
//                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
//                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
//                        .addGap(162, 162, 162))
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(delete3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(360, 360, 360))
//                    .addGroup(jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGap(8, 8, 8)
//                                .addComponent(name)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(contact)
//                                .addGap(18, 18, 18)
//                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(email)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(29, 29, 29)
//                                .addComponent(address)
//                                .addGap(18, 18, 18)
//                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                    .addGroup(jPanel2Layout.createSequentialGroup()
//                                        .addComponent(price)
//                                        .addGap(61, 61, 61)
//                                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addGroup(jPanel2Layout.createSequentialGroup()
//                                        .addComponent(proId)
//                                        .addGap(18, 18, 18)
//                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addGap(18, 18, 18)
//                                .addComponent(proName)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(proQty)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(22, 22, 22)
//                                .addComponent(category)
//                                .addGap(18, 18, 18)
//                                .addComponent(proCat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                        .addContainerGap(35, Short.MAX_VALUE))))
//        );
//        jPanel2Layout.setVerticalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(date)
//                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(time))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(billNo))
//                .addGap(18, 18, 18)
//                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(28, 28, 28)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(name)
//                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(contact)
//                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(email)
//                    .addComponent(address)
//                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(5, 5, 5)
//                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(11, 11, 11)
//                .addComponent(prodetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(proId)
//                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(proName)
//                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(proQty)
//                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(category)
//                            .addComponent(proCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(18, 18, 18)
//                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(price)
//                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(100, 100, 100)
//                        .addComponent(total))
//                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(28, 28, 28)
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(delete3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
//        );
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(46, 46, 46)
//                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(68, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addGap(20, 20, 20)
//                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGap(20, 20, 20))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGap(0, 0, Short.MAX_VALUE)
//                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//    }// </editor-fold>                        

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing_Point().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Paid;
    private javax.swing.JLabel Return;
    private javax.swing.JButton add;
    private javax.swing.JLabel address;
    private javax.swing.JLabel billNo;
    private javax.swing.JTextField bill_no;
    private javax.swing.JLabel caldetail;
    private javax.swing.JLabel category;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JButton clear;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField cus_name;
    private javax.swing.JButton delete;
    private javax.swing.JLabel dt;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel name;
    private javax.swing.JLabel price;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel proName;
    private javax.swing.JLabel proQty;
    private javax.swing.JTextField prodetail;
    private javax.swing.JTextField productIdTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JLabel proid;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton save;
    private javax.swing.JLabel tme;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
